version: '3.8'

services:
  # Ollama сервис для локальной LLM
  ollama:
    image: ollama/ollama:latest
    container_name: ai-masters-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Python бот приложение
  ai-masters-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-masters-bot
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3}
      - DATA_DIR=/app/data
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://ollama:11434/api/version')"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 60s

volumes:
  ollama_data:
    driver: local

networks:
  default:
    name: ai-masters-network 